name: C/C++ CI

on:
  push:
    branches: [ "main", "nemirko" ]
  pull_request:
    branches: [ "main", "nemirko" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Установить зависимости
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev cmake

    - name: Собрать GoogleTest
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib

    - name: Собрать проект и тесты
      run: |
        g++ -std=c++17 -I/usr/include/gtest -pthread main.cpp tests/test_column.cpp -lgtest -lgtest_main -o test_column

    - name: Запустить тесты
      run: ./test_column
