name: C/C++ CI

on:
  push:
    branches: [ "main", "nemirko" ]
  pull_request:
    branches: [ "main", "nemirko" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Установить зависимости
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev cmake

    - name: Собрать GoogleTest
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Собрать проект и тесты
      run: |
        g++ -std=c++17 -DUNIT_TEST -I/usr/include/gtest -pthread device.cpp tests/test_column.cpp -lgtest -lgtest_main -o test_column

    - name: Запустить тесты
      run: ./test_column

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: 74c058b9-023b-4897-9087-88c6ce74189c
        files: coverage.info
        flags: unittests
        name: codecov-report
        fail_ci_if_error: true
