name: C/C++ CI

on:
  push:
    branches: [ "main", "nemirko" ]
  pull_request:
    branches: [ "main", "nemirko" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Установить зависимости
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make

    - name: Собрать основную программу
      run: make

    - name: Собрать и запустить тесты
      run: make test

    - name: Проверить основную программу
      run: |
        ./chemical_process | head -10
        echo "Основная программа работает"

  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Проверка качества кода
      run: |
        # Проверяем, что нет файлов с расширением .o или исполняемых файлов в репозитории
        if find . -name "*.o" -o -name "a.out" -o -name "chemical_process" -o -name "run_tests" | grep -q .; then
          echo "Найденные файлы:"
          find . -name "*.o" -o -name "a.out" -o -name "chemical_process" -o -name "run_tests"
          echo "ОШИБКА: В репозитории не должно быть скомпилированных файлов!"
          exit 1
        fi
        echo "Качество кода: OK - в репозитории нет скомпилированных файлов"
